name: Sync-Images-to-ACR
run-name: ${{ github.actor }} is Sync Images to Aliyun Container Registry (ACR)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3

    - name: Login to Aliyun Container Registry (ACR)
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Sync Image to ACR
      run: |
        #!/usr/bin/env bash
        IMG=( bitnami/kafka:3.6.1-debian-11-r0
        )
        for i in ${IMG[@]}; do
           docker pull $i
           Name=$(echo $i|awk -F'/' '{print $NF}')
           docker tag $i ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}/midoss/$Name
           docker push ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}/midoss/$Name
        done
