name: Sync-Images-to-ACR
run-name: ${{ github.actor }} is Sync Images to Aliyun Container Registry (ACR)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3

    - name: Login to Aliyun Container Registry (ACR)
      uses: aliyun/acr-login@v1
      with:
        login-server: https://registry.cn-beijing.aliyuncs.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        logout: false
        
    - name: Sync Image to ACR
      run: |
        #!/usr/bin/env bash
        IMG=( registry.opensource.zalan.do/acid/postgres-operator:v1.10.1 ghcr.io/zalando/spilo-15:3.0-p1 registry.opensource.zalan.do/acid/logical-backup:v1.10.1 registry.opensource.zalan.do/acid/pgbouncer:master-27
        )
        for i in ${IMG[@]}; do
           docker pull $i
           Name=$(echo $i|awk -F'/' '{print $NF}')
           docker tag $i registry.cn-beijing.aliyuncs.com/midoss/$Name
           docker push registry.cn-beijing.aliyuncs.com/midoss/$Name
        done
